- Project Files/Source/Console/PSForm.cs
- Project Files/Source/Console/console.cs
Fixes : #48 
Also, I noticed that PS-A was not locking/calibrating under the following conditions :
1) PS-A off
2) Step att set to change to 31dB on tx
3) Mox pressed
4) Then PS-A on
5) Wouldnt lock unless I moved step atten
Discovered that hiprio call has been removed from NetworkIO.SetPureSignal so a call to SendHighPriority(1) just after SetPureSignal call inside PSEnable (psform) and it seems to have fixed the issue.
> Fix stepAtt issue and HiPriority packet test

- Project Files/Source/Console/DiversityForm.cs
- Project Files/Source/Console/DiversityForm.resx
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
1) PA19.Initialise is performed in thread so it can happen as remainder of thetis is starting up
2) CPUload performance counters are also in own thread at initialisation as they can be very slow to obtain (8-10 seconds)
3) Setupform now parented to Thetis form, so it will never go behind
4) Re-enabled the VFO Sync button on Diversity form as many users confused why diversity is not working as expected when rx2 is elsewhere
5) Multi rx lost audio at startup fix/work around
> Setupform changes, diversity sync and some g7klj improvments

- Project Files/Source/Console/HPSDR/NetworkIOImports.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
There is support in the Saturn p2app for this bit 5 to control whether to choose
3.5mm or XLR mic inputs.
> Adding support for Saturn Mic Input, XLR / 3.5mm

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/console.cs
Now returns MKII volts., otherwise will always be 00.0 unless radio is HPSDR where it return a parse error (maintain previous behaviour).
Format returned
ZZRV00.0;
https://github.com/ramdor/Thetis/issues/143
> Changes to ZZRV

- Project Files/Source/Console/display.cs
- Project Files/Source/Console/titlebar.cs
Fixes issue if RX2 is shown then RX1 tracks the noise floor incorrectly from time to time. RX1 and RX2 were sharing same data copy incorrectly.
> Incorrect display buffers used when RX2 enabled

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/CAT/CATParser.cs
- Project Files/Source/Console/CAT/CATStructs.xml
- Project Files/Source/Console/Midi2CatCommands.cs
- Project Files/Source/Console/console.Designer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/console.resx
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/Midi2Cat/Midi2Cat.Data/CatCmdDb.cs
Quick Split option when using rx1 only. Added ZZZN and ZZZO, as well as midi support. Config in options2 tab, or right click split button. Shift left click split button to enable QPLT when only rx1 enabled.
> Quick Split Added

- Project Files/Source/Console/console.Designer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/console.resx
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
PA profile now visible for all modes, and also on collapsed view (under smeter). Can also right click the profile to bring up setup window.
Also, new noise floor calculation method where dbm are linearised then averaged. Results in more accurate smoother calculation of nf. Option to set it in options 2 tab
> PA profile on all modes and new noise floor calc method

- Project Files/Source/Console/AssemblyInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/titlebar.cs
1) colours now set on some controls when a fresh db is used. There would always be some grey boxes in the vfos on a fresh without a db
2) assembly version changed to v2.10.2 in readiness for pre-release
> final push for v2.10.2 + fix for colours not being set on fresh db

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/titlebar.cs
1) Issue fixed where control name was the same in two forms but different colours etc. Now uniquely keyed to fix this issue. 
2) Added smooth fade over 500ms for meter items that have fade TX/RX enabled
> FIX Highlight control + Smooth meter item fade

- Project Files/Source/Console/console.Designer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/console.resx
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
1. Option in appearance->meter to turn off legacy meters 
2. VFOtx space bar toggle options in setup->keyboard
3. Fixes for noise floor fast attack time. Resizing can result in low frame rates which would cause problems for the fast attack. Now based on ms elapsed and not frame count
4. Moving MasterAF slider will unmute like the other sliders. Uses setting in setup-audio-options (rx1 only, this might need changing)
> Legacy meter enable/disable, VFOtx toggle on spacebar, some other fixes

- Project Files/Source/Console/MeterManager.cs
Re-worked fade code and now covers each meter item with a rectangle the same colour as the mm container. The alpha of this rectangle is then modified to simulate fade. Improved when used against a coloured container background.
> Update to multimeter fade implementation

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/CAT/CATParser.cs
- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/TCIServer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/titlebar.cs
1. quick split audio pan
2. quick split disable when cat/tci split message option 
3. fix for when magic eye bezel and eye are different scales
4. added report for tx profile changes, click on the orange box
> Quick split + Fade eye scale + TXprofile change report

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
1. multimeter fixes for zeroing meters
2. volts clear to 0 when power off
3. meters reset to minimum when power on/off
4. all dictionary code fixed where we want first or last item
5. added code to adjust width of txprofile report window
> Multimeter fixes, volts clear down, dictionary oldest key fixes, etc

- Project Files/Source/Console/console.cs
Fix : With radios that can step_att > 31. They would not correctly return to a high step att after MOX. This resolves #140.
> Fix when mox off and step att > 31

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/ucMeter.cs
- No title bar for meter container option
- CW auto swap has been improved, now handles rx2, and has option in setup to return to previous mode after a duration
- meter items will fade if not in use in console. For example, turn off TXeq and the EQ meter will fade out
> No title bar meter container, improvements to auto CW swap, meter item disable

- Project Files/Source/Console/HPSDR/specHPSDR.cs
- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/wdsp/analyzer.c
- Project Files/Source/wdsp/analyzer.h
RxDisplayCalibration offset is now applied when in DUP mode TX on rx1. Fixes issue #137 
WDSP SnapSpectrum can infinite wait, added time out options
Multimeters would not reset to S0 when above 30MHz. Now fixed.
> DUP TX Offset, WDSP SnapSpectrum timeout, Multimeter zeroout fix

- Project Files/Source/Console/clsThetisSkinService.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/Midi2Cat/Midi2Cat.IO/MidiDevice.cs
- Project Files/Source/ReleaseNotes.txt
- skin server now works with redirects
- phase reverse now can be turned on/off (ooops)
- midi control ID can now also include status to make it 24 bit
> skin server uri redirect handled, phase reverse, midi status

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/setup.cs
- bypass change events when tx profile checker is running via timer
- remove bunch of pointless comments
> bypass change events when tx profile checker is running via timer

- Project Files/Source/ChannelMaster/netInterface.c
- Project Files/Source/ChannelMaster/network.c
- Project Files/Source/ChannelMaster/network.h
- Project Files/Source/Console/HPSDR/Alex.cs
- Project Files/Source/Console/HPSDR/NetworkIOImports.cs
this adds sending the selected ANT1-3 bits through the High Priority Packet. New SDR firmware will use this to decide which ANT to select BEFORE going into TX. Older SDR firmware will still operate the same selecting the ANT after going to TX.
> Adding fix for 'Investigate power (CW) appearing on rx only ports #228'

- Project Files/Source/ChannelMaster/netInterface.c
I meant to use an '|=' instead of plain ole '=' otherwise the BPF2 settings
get stepped on (cleared). This was causing low to non-existent RX signals
on adc1 / rx2.
> Fix broken BPF2 settings

- Project Files/Source/Console/cwx.cs
notes from Chris W2PA :
I made a minor change to CWX that makes it much more usable in DX pileups and other scenarios where you want it to behave like a memory keyer.  I mapped F1 through F9 to the messages 1 thru 9, and moved the two functions previously on F1 and F2 up to F11 and F12.  I changed the form to indicate it, too.  The old behaviour with the Alt key remains unchanged for anyone who prefers it.
Now, without any shift key or mouse selection/clicking, the messages are instantly sent at will.  I’ve used it in DX pileups and it works well.
> Fn key changes to CWX

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/CAT/CATParser.cs
- Project Files/Source/Console/CAT/CATStructs.xml
- Project Files/Source/Console/Midi2CatCommands.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Midi2Cat/Midi2Cat.Data/CatCmdDb.cs
- Project Files/Source/ReleaseNotes.txt
- [add] zzxa cat command to get/set audio amplifier (rear speaker sockets). zzxa1; to enable, zzxa0; to disable (github #308)
- [add] midi button command to toggle audio amplifier (rear speaker sockets) (github #308)
> zzxa and related midi

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/setup.designer.cs
fixes for multimeters where initial/zeroed values would be incorrect, such as -195mic, and -19:0swr
> mm fixes for zero state
