- Project Files/Source/Console/AssemblyInfo.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/progress.cs
- Project Files/Source/Console/progress.resx
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/titlebar.cs
This is the start of the work on multi meters.
This commit contains fixes 'hacks' for the mouse wheel when using width/shift sliders (not 100% happy with the solution)
Also, RX2 level calibration, and reset ability.
Fix for flickering of controls that have no exposed doublebuffered property. Now function in Common to try and use reflection to achieve this.
> 2.9.0.6 pre-release

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/Midi2CatCommands.cs
- Project Files/Source/Console/console.Designer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/console.resx
- Project Files/Source/Console/frmBandStack2.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/Console/ucInfoBar.cs
- Project Files/Source/Midi2Cat/Midi2Cat.Data/CatCmdDb.cs
-fix: CAT TX will now be turned off if MOX/Power is pressed and system was previously in a MOX/TX state (note: if you manual mox, you will not be able to un PTT via cat)
-fix: some additional null checks in ucInfoBar
-fix: Tune was not using cw_pitch correctly when in CW. Issue introduced in 21d
-add: option to swap vfo wheels in midi
-add: Ukraine flag turned off. Now there is a setting option to support Ukraine
> Day 1 return

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/PSForm.cs
- Project Files/Source/Console/audio.cs
- Project Files/Source/Console/cmaster.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/enums.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
request to merge Laurence Barker G8NJJ updates to add support for Anan-G2
Generally set the same as ANAN-7000D except RX signal levels different, and puresignal peak constant is different
> Anan-G2 additions

- Project Files/Source/Console/console.cs
added ANAN_G2 and ANAN_G2_1K
(Current scaling is not yet working though - RF board may have changed)
> updated readMKIIPAVoltsAmps() for Saturn

- Project Files/Source/Console/AssemblyInfo.cs
- Project Files/Source/Console/PSForm.cs
- Project Files/Source/Console/audio.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/enums.cs
- Project Files/Source/Console/titlebar.cs
changes to the setdefaulpeaks for PS, assembly version change to 2.9.1 so we can test DB import/update, tag for WIP added on titlebar
> Version update, and some changes to PS peak settings recovery

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
just a couple of changes that I want to put into master before I work on the rit/xit fixes
> changes pre rix/xit work

- Project Files/Source/Console/KE9N/spot.cs
- Project Files/Source/Console/RAForm.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/ucInfoBar.cs
- Project Files/Source/Console/ucLGPicker.cs
- Project Files/Source/Console/wave.cs
Remove the requirement for Arial in certain UI controls
> Move Arial fonts to Microsoft Sans Serif

- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/console.cs
fixes isses raised in : https://github.com/ramdor/Thetis/issues/145
> Mode settings form fix

- Project Files/Source/Console/Andromeda/Andromeda.cs
Hopefully this will solve the issue of it not changing the panel
> Change to ModeSpecificWindow code

- Project Files/Source/Console/Andromeda/Andromeda.cs
> ModeSpecificForm changes

- Project Files/Source/Console/ucInfoBar.cs
Seemed to have resolved the issue reported here #149
> Fix for korea japan resize issue

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
1) added fade in for main console window and meter containers
2) added code to wait for getInstanceName thread
3) some slight/minimal frame rate improvements to panadaptor renderer in display.cs
> Various changes

- Project Files/Source/Console/TCIServer.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
1) Button to clear spots on the TCI setup form area 2) spot_clear;  tci command added
> TCI spot clear support

- Project Files/Source/Console/console.cs
Adding/removing a couple of controls from the highlight
> TX Profile highlight update

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/TCIServer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/database.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/titlebar.cs
Fixes all issues related to RIT and XIT. Also fixes an issue when dup+ctun+split were used and the filter/grid were incorrectly aligned.
**This branch could do with being built by those that can, and tested. There may be something I have missed. Thanks.**
> Dup ctun split fix and rit xit fixes

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
Issue causing radio to always initialise on start up. ADC's were being reset to default.
> Fix RadioModel init state

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
Fixed problem where PA profile not selected correctly after an import/fresh db
> Fix to PA profile selection on initial start up

- Project Files/Source/Console/console.cs
new pa label in collapsed view would not hide if top or top andromeda controls hidden
> Fix pa label not hiding

- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
Added tooltips to qsplit controls in setup
> Tool tips added to new qsplit controls

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
> Linked AF Sliders

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
fixes for fade with magic eye
added txprofile change report, click the orange box in setup
> FadeFixes, TXProfile change Report

- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Thetis-Installer/Product.wxs
Line showing you are in a band at top of grid, option in appearance->rx display->join band edges
**NOTE: change to wix installer to uninstall and then install**
> Join band edges with a line at top of grid + Wix installer change

- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/Andromeda/ModeDependentSettingsForm.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Fix for #201
- Added CTRL option for linked AF sliders
- removed old RX1/RX2 link code
- prevent TXprofile check timer when saving/loading options
> Late changes and fix for #201

- Project Files/Source/Console/KE9N/spot.cs
- Project Files/Source/Console/TCIServer.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/cwx.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/enums.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/titlebar.cs
TCI obeys disable ptt
CWX obeys disable ptt
> Final fixes for release

- Project Files/Source/Console/PSForm.cs
- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/database.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/eqform.cs
- Project Files/Source/Console/frmFinder.cs
- Project Files/Source/Console/radio.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/wdsp/analyzer.c
- Project Files/Source/wdsp/calcc.c
- Project Files/Source/wdsp/calcc.h
Merging the changes made to 2.10.3 dev. A new branch is also needed for some other fixes before 2.10.3 gets released, probably 2.10.3-dev1
> v2.10.3 dev

- Project Files/Source/ChannelMaster/aamix.c
- Project Files/Source/ChannelMaster/cmUtilities.c
- Project Files/Source/ChannelMaster/cmbuffs.c
- Project Files/Source/ChannelMaster/netInterface.c
- Project Files/Source/ChannelMaster/network.c
- Project Files/Source/ChannelMaster/networkproto1.c
- Project Files/Source/ChannelMaster/obbuffs.c
- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/BasicAudio.cs
- Project Files/Source/Console/CAT/TCPIPcatServer.cs
- Project Files/Source/Console/TCIServer.cs
- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/cwx.cs
- Project Files/Source/Console/database.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/frmFinder.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/wdsp/analyzer.c
- Project Files/Source/wdsp/calcc.c
- Project Files/Source/wdsp/channel.c
- Project Files/Source/wdsp/main.c
- Project Files/Source/wdsp/syncbuffs.c
- Project Files/Source/wdsp/utilities.c
- fixes to the cwx problem where RF is on a port configured as RX only were removed as not happy with them. Fixes to the key/memory buttons so that they disable when power turned off we left in
- cfc improvents, auto scale removed. Note the line that shows the CFC profile is scaled to fit the window height, but if showing 30dB worth it will be 1 to 1
- threads named throughout to better track issues
- importDB notch 'fixed' again
> v.2.10.3 dev1

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.Designer.cs
- Project Files/Source/Console/console.resx
another attempt, so here we go. Hopefully ;-)
> Gui realignment

- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/CAT/SIOListenerII.cs
- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/Console/wave.cs
- SIOListenerII - removed strange use of Activate event, and the locking which is not necessary as far as I can tell 
- System CPU usage change
> Changes to SIOListenerII and CPU usage

- Project Files/Source/ChannelMaster/ChannelMaster.vcxproj
- Project Files/Source/Console/frmReleaseNotes.cs
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/ReleaseNotes.txt
- Project Files/lib/portaudio-19.7.0/build/msvc/portaudio.vcxproj
Hopefully the final commit for v2.10.3
fixed x86 build/debug issues
> Final push for v2.10.3

- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
> setup-cosmetics

- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
Again a few small adjustments all over the setup layout. Nothing major, a few pixels here and there.
Somehow I always find something. But I think I'm done with it for now.
> setup overhaul

- Project Files/Source/ChannelMaster/ChannelMaster.vcxproj
- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/cmASIO/cmASIO.vcxproj
- Project Files/Source/wdsp/wdsp.vcxproj
- Project Files/lib/portaudio-19.7.0/build/msvc/portaudio.vcxproj
- sse2 removed from x64 release/debug in all projects/subprojects
- array bounds check for various in getstate()
- tri state protocol checkbox changed to radio buttons
> sse2 remove, getstate array bounds, tri state checkbox for protocol removed in setup

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/ucMeter.cs
- Project Files/Source/ReleaseNotes.txt
- implement #87
- implement #306
- a disabled multimeter will not process readings or render
- removed mid/hight waterfall colourpickers as not used anymore
> multiple changes

- Project Files/Source/ChannelMaster/cmasio.c
- Project Files/Source/Console/cmaster.cs
int cmaster.GetCMAstate()
0 = not in use | 1 = in use | -1 = failed
> method for cmASIO status bar icon

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/audio.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/ReleaseNotes.txt
scope handles tx/rx sample rate differences
scope time now defines how quick to fill the display width
> scope changes

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/audio.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/ReleaseNotes.txt
- autostart option in options2 tab
- buttons to copy min/max spec grid and high/low waterfall values to all other bands in display rx1/rx2
> autostart option, copy min/max high/low values

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/display.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
nf is not adjusted when normalising pbsnr. There are now offset values to the pbsnr that can be used instead if required
> pbsnr NF change, some clean up of display.cs

- Project Files/Source/Console/console.resx
to match panelOptions regarding the lateral distance.
> rearanged and centered panelSoundControls

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
Majority of commented/dead code removed from console.cs
This is likely to cause many issues for branches/forks of Thetis, but it needed to be done. Next up will be setup.cs, followed by display.cs.
These others will be done for 2.10.3.5-pre-release-6
Note: fix for rx2 sql paint
> console.cs dead code clean

- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.resx
in my last pullrequest I forgot to move picSquelch
> picSquelch moved

- Project Files/Source/Console/display.cs
removed all commented/dead code
> display.cs code clean

- Project Files/Source/Console/console.resx
> dRX2StepAttData.Location

- Project Files/Source/ChannelMaster/netInterface.c
- Project Files/Source/ChannelMaster/network.c
- Project Files/Source/ChannelMaster/network.h
- Project Files/Source/Console/HPSDR/NetworkIOImports.cs
- Project Files/Source/Console/VersionInfo.cs
- Project Files/Source/Console/console.cs
added SetCATPort to DLL; added handler
added port address to bytes 1398, 1399
> added CAT over TCPIP to P2 high priority data message

- Project Files/Source/ChannelMaster/netInterface.c
- Project Files/Source/ChannelMaster/network.h
- Project Files/Source/Console/HPSDR/NetworkIOImports.cs
- Project Files/Source/Console/console.cs
It's the last 2 commits that matter, the 1st was reverted.
BTW, these are changes that Laurence / G8NJJ had sent me.
> Updates to fix issue #407

- Project Files/Source/Console/TCIServer.cs
fix bunch of buffering issues when rx'ing TCI data
> Tciserver buffer

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
Kenwood AI port selection options, implements #430
Note, if you had AI turned on previously, then you will now need to also turn on 'port 1'
> Kenwood AI port select options

- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
https://github.com/ramdor/Thetis/issues/385
> implement zzoa and zzoc, for get/set

- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/xvtr.cs
- Project Files/Source/ReleaseNotes.txt
New option to select antenna for the LO band which implements #424. See vid : https://www.youtube.com/watch?v=FYhDYbqnx3c
This could do with some testing before this branch is included. There may be edge cases I have missed.
> Xvtr antenna

- Project Files/Source/Console/DiversityForm.cs
- Project Files/Source/ReleaseNotes.txt
- shift click to store
- ctrl click to clear
> diversity memory buttons

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/ucMeter.cs
https://github.com/ramdor/Thetis/issues/104
> ability to store notes with a multimeter container

- Project Files/Source/Console/titlebar.cs
- Project Files/Source/ReleaseNotes.txt
issue where multimeters would sometimes no reset to low values when shutting down/changing band etc. Now resolved.
> Fixes mm zerostate

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/ReleaseNotes.txt
new options to prevent PS from disabling the BFS
> option to prevent PS from disabling BFP

- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
in options tab, auto start up
has a few options
1) only start if not in process list
2) try to close down any thetis has started up
> config options for up to 10 pieces of software to be loaded by thetis

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
The start of adding data io to multimeters via tcp/ip and udp
> network manager

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
now possible to control the rotator from the multimeter item, click,drag,release
> rotator control

- Project Files/Source/Console/Andromeda/Andromeda.cs
- Project Files/Source/Console/Andromeda/AndromedaEditForm.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
windiff branch with master, as setup had diverged too much
> G2 andromeda panel support - diff merge

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/console.cs
you can now click on the band text on the vfo display multimeter item to show bands. Early implementation.
> band selector

- Project Files/Source/Console/clsDBMan.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/database.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/titlebar.cs
removed old db import and upgrade code
removed reset / import / export buttons from setup fixed -ve values for beamwidth, now lowest is 0
added import log output files in app_data_path, two files
- ImportLog.txt   for regular import
- ImportLog_dbupdate.txt   for a db that has been updated due to version
> import log + old db import removed

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/clsDBMan.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/ReleaseNotes.txt
can now pick vfoa, vfob or both for the mm vfo meter item
> Mm vfo update

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/cwx.cs
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/ReleaseNotes.txt
F1 through to F12, and a few other keys are handled by the CWX form even without focus if the Focus check box is disabled.
> cwx no focus required

- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- some typo fixes
- nasa/noaa not limited to 600 seconds
- zoom bar position fix when returning from collapsed and using legacy removal
> zoom bar, nasa/noaa, typos

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/titlebar.cs
- prevent mode changes when in tx
- prevent band changes when in tx
> no band or mode change on tx fixes

- Project Files/Source/Console/MeterManager.cs
- Project Files/Source/Console/Thetis.csproj
- Project Files/Source/Console/Thetis.csproj.user
- Project Files/Source/Console/audio.cs
- Project Files/Source/Console/clsCMASIOConfig.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
- Project Files/Source/Console/setup.resx
- Project Files/Source/Console/titlebar.cs
- Project Files/Source/Console/ucMeter.cs
- Project Files/Source/ReleaseNotes.txt
- Project Files/Source/cmASIO/hostsample.cpp
- Project Files/lib/portaudio-19.7.0/src/hostapi/asio/pa_asio.cpp
use -cmasioconfig  as a command line parameter to enabled the cmASIO tab in Audio settings
> Cmasio config

- Project Files/Source/ChannelMaster/network.h
- Project Files/Source/Console/CAT/CATCommands.cs
- Project Files/Source/Console/clsHardwareSpecific.cs
- Project Files/Source/Console/cmaster.cs
- Project Files/Source/Console/common.cs
- Project Files/Source/Console/console.cs
- Project Files/Source/Console/enums.cs
- Project Files/Source/Console/setup.cs
- Project Files/Source/Console/setup.designer.cs
Adding the Anvelia-Pro3 in Thetis so it can have its own profile.
I used the filter-container branch as it is the latest in development.
> Adding ANVELINA-PRO3 model to Thetis
